# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

a = [1, 2]
x = 0
while x <= 4000000
	
	x = a.fetch(-1)
	y = a.fetch(-2)
	
	a << (x+y)	
	x = a.fetch(-1)
end
	a.pop
	
	a.each{
		|b|
		if b%2 != 0
			a.delete(b)
		end
		}
	
puts a
q = 5 % 2
puts q